### ISSUE TITLE
tak ada satuan pada tampilan data

### ISSUE THREAD

**Issue by elberthomax** [elberthomax/Tabel_Periodik#6]
quote "besaran tak berarti tanpa satuan"
![satuan](https://user-images.githubusercontent.com/38391861/39188978-adac26ae-4803-11e8-84c7-a9468d06dc04.png)

**Comment by kvnchandra** [comment]
mau di tambai satuannya ini??

**Comment by elberthomax** [comment]
ya ._. ngamuk nanti orang fisika/kimia klau tdk ada

**Comment by stevelukis** [comment]
di judul tab saja yg ditambah atau di data xmlnya? kalau misalnya di data xml, mending sekalian arif saja yg kerja

**Comment by stevelukis** [comment]
@elberthomax @kvnchandra oi hurry up, nanti terlanjur banyakmi na isi arif hahaha

**Comment by kvnchandra** [comment]
di tab nya mo kayaknya karna banyak ki yg mw ditambai

**Comment by stevelukis** [comment]
sip

**Comment by stevelukis** [comment]
edit mko langsung html nya @kvnchandra

**Comment by kvnchandra** [comment]
bgmn caranya edit?? download dlu ato bgmn??

**Comment by stevelukis** [comment]
pull dulu atau clone. baru edit di laptopmu. kalau sudah, commit baru push.

**Comment by kvnchandra** [comment]
sdh mi satuannya
